[project]
name = "2025-09-19-measure-hnet-cossim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "omegaconf>=2.3.0",
    "torch>=2.8.0",
]
